### PR TITLE
update XSL transformation to format the gmd:dateStamp to YYYY-MM-DDTHH:MM:SS

### PR DESCRIPTION
**Pull request by alexarobu**
This is to match what DGU expects. Stripping out the milliseconds and timezone that gets added in GeoNetwork 4.x

fixes issue #147

### CODE REVIEW

**Comment by alexarobu** [comment]
@archaeogeek I already deployed this to the [osmetadata](https://osmetadata.astuntechnology.com/geonetwork/srv/eng/catalog.search#/home) portal and it seems it improved the harvesting to DGU for them.

**Review by archaeogeek — APPROVED** [review]
Looks good. It might be a good idea to add this to the other profiles based on Gemini as well- bearing in mind that I think there's already some code in the appropriate file for NRW to do something similar, so maybe you just need to check their records validate OK

**Comment by alexarobu** [comment]
@archaeogeek thank you! :smiley:

**Comment by alexarobu** [comment]
@archaeogeek :frowning_face: looks like this change introduced an issue in the standard. before this was implemented the gmd:dateStamp was getting automatically updated when you were creating or changing a record, now it gets stuck to whatever is in the record already (the date in the template if it's a new record or the existing date if you edit a record). It's definitely caused by this change because all our portals suffer from this and I tested locally by removing the change and the date gets automatically updated again. I am not entirely sure how to fix it yet, any ideas would be greatly appreciated as always :pray:

**Comment by PeterParslow** [comment]
Also, data.gov.uk tell me that they've fixed this issue at their end - and you can see some proof of that at https://[ckan.publishing.service.gov.uk/harvest/object/1dd2353a-8400-40e1-babe-7a86b781f2b3](https://ckan.publishing.service.gov.uk/harvest /object/1dd2353a-8400-40e1-babe-7a86b781f2b3)

So for OS, I'd prefer to fix the current issue by removing the fix to this issue. 

Longer term, it might be useful to allow people to choose to round their date stamps or not.

**Comment by alexarobu** [comment]
@PeterParslow I fixed the issue now, please test and let me know if you still face any issues.

**Pull request merged**
